version: '3'
networks:
  minharede:
    driver:
      bridge
services:

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    entrypoint: dockerize tcp://db:3306 -timeout 30s bash -c "./docker-entrypoint.sh"
    container_name: nodejs
    hostname: nodejsserver
    volumes:
      - ./nodejs:/app
    depends_on:
      - db
    links:
      - db
    networks:
      - minharede
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - nodejs
    networks:
      - minharede

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbnode
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
    networks:
      - minharede
